packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  '@parcel/watcher': false
  '@sentry/cli': false
  better-sqlite3: true
  esbuild: false
  sharp: false
  vue-demi: false

overrides:
  sharp: 0.33.4
